[package]
name = "ruvolt"
description = "An API wrapper for Revolt written in Rust."
version = "0.1.0"
authors = ["Arthur Damasceno <damascenoarthur653@gmail.com>"]
repository = "https://github.com/Arthur-Damasceno/ruvolt"
license = "MIT"
edition = "2021"

[dependencies]
async-trait = "0.1"
