[package]
name = "ruvolt"
description = "An API wrapper for Revolt written in Rust."
version = "0.1.0"
authors = ["Arthur Damasceno <damascenoarthur653@gmail.com>"]
repository = "https://github.com/Arthur-Damasceno/ruvolt"
license = "MIT"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1.15", features = ["time", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.16", features = ["rustls-tls-webpki-roots"] }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "json"]

[dev-dependencies]
tokio = { version = "1.15", features = ["macros"] }
